version: '3.8'
services:
  neo4j:
    image: neo4j:5.11
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password123 # 사용자명/비밀번호
      - NEO4J_PLUGINS=["graph-data-science"]
    volumes:
      - neo4j_data:/service

  qdrant:
    image: qdrant/qdrant:v1.7.4
    ports:
      - "6333:6333" # gRPC
      - "6334:6334" # REST
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  neo4j_data:
  qdrant_data: